### ISSUE TITLE
PyTwat freaks out upon reaching end of tweets.txt

### ISSUE THREAD

**Issue by closeta** [closeta/pytwat#1]
Once the script reaches the bottom of the tweets file, it attempts tweeting nothing, leading to the error below.

```python
 Traceback (most recent call last):
  File "pytwat.py", line 36, in <module>
    api.update_status(file.readline())
  File "/usr/lib/python3.5/site-packages/tweepy/api.py", line 194, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/usr/lib/python3.5/site-packages/tweepy/binder.py", line 229, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'message': 'Missing required parameter: status.', 'code': 170}]
```

**Comment by closeta** [comment]
Hmm, this bug appears to be fixed. Closing for the moment.
